"""
The Part XVII figures that require training.

    python3 train_figures.py

Everything here trains on a synthetic source whose entropy rate is computed in
closed form. That is the point: a scaling law's irreducible term E is supposed
to be the entropy of the data, and on real corpora nobody can check. Here we
can, so the fit has a right answer rather than a plausible one.

Three questions:

  * does a fitted power law recover the true entropy as its irreducible term?
  * does the learning-rate schedule error reproduce, and does it move the
    inferred compute-optimal allocation the way Chinchilla said it did?
  * what does a mixture-of-experts router actually do to load balance?
"""
import os
import sys

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from make_figures import (save, tidy, plt, STUDY_OUT, BLUE, ORANGE, GREEN,  # noqa: E402
                          PURPLE, PINK, GRAY, LIGHT, INK, CYAN)

torch.set_num_threads(4)

V, ORDER = 16, 3
N_CTX = V ** ORDER


# ------------------------------------------------- the source, and its entropy

def make_source(seed=0, hidden=64, temp=0.12):
    """An order-3 source generated by a fixed random TEACHER network.

    The conditional for each of the 4096 contexts is a smooth function of the
    three symbols' embeddings, so the source has compositional structure that
    more capacity captures progressively. A source with independent Dirichlet
    conditionals per context has no such structure — it is a lookup table, and
    a student either memorises it or learns nothing, which produces no power
    law at all. That version was tried first and is why this one exists.
    """
    r = np.random.default_rng(seed)
    Emb = r.normal(size=(V, 12)) / np.sqrt(12)
    W1 = r.normal(size=(36, hidden)) / np.sqrt(36)
    b1 = r.normal(size=hidden) * 0.1
    W2 = r.normal(size=(hidden, V)) / np.sqrt(hidden)
    ctxs = np.arange(N_CTX)
    a = ctxs // (V * V)
    b = (ctxs // V) % V
    c = ctxs % V
    X = np.concatenate([Emb[a], Emb[b], Emb[c]], 1)          # (N_CTX, 36)
    Hd = np.tanh(X @ W1 + b1)
    L = (Hd @ W2) / temp
    L -= L.max(1, keepdims=True)
    P = np.exp(L)
    return P / P.sum(1, keepdims=True)


def entropy_rate(P, iters=4000):
    """Exact entropy rate, in nats per symbol.

    H = sum_c pi(c) H(P[c]) where pi is the stationary distribution over
    contexts. The context chain is deterministic given the emitted symbol:
    context (a,b,c) emitting v moves to (b,c,v).
    """
    nxt = np.empty((N_CTX, V), dtype=np.int64)
    for c in range(N_CTX):
        b = (c % (V ** 2)) * V
        nxt[c] = b + np.arange(V)
    pi = np.full(N_CTX, 1.0 / N_CTX)
    for _ in range(iters):
        new = np.zeros(N_CTX)
        np.add.at(new, nxt.ravel(), (pi[:, None] * P).ravel())
        new /= new.sum()
        if np.abs(new - pi).max() < 1e-14:
            pi = new
            break
        pi = new
    Hc = -(P * np.log(np.clip(P, 1e-30, None))).sum(1)
    return float((pi * Hc).sum()), pi


def sample_source(P, n_tokens, seed=0):
    r = np.random.default_rng(seed)
    out = np.empty(n_tokens, dtype=np.int64)
    c = int(r.integers(0, N_CTX))
    U = r.random(n_tokens)
    C = P.cumsum(1)
    for i in range(n_tokens):
        v = int(np.searchsorted(C[c], U[i]))
        v = min(v, V - 1)
        out[i] = v
        c = (c % (V ** 2)) * V + v
    return out


# ------------------------------------------------------------------ the model

class Tiny(nn.Module):
    def __init__(self, d, L, heads=2, ctx=64):
        super().__init__()
        self.emb = nn.Embedding(V, d)
        self.pos = nn.Embedding(ctx, d)
        self.blocks = nn.ModuleList()
        for _ in range(L):
            self.blocks.append(nn.ModuleDict(dict(
                n1=nn.LayerNorm(d), n2=nn.LayerNorm(d),
                att=nn.MultiheadAttention(d, heads, batch_first=True),
                ff=nn.Sequential(nn.Linear(d, 4 * d), nn.GELU(),
                                 nn.Linear(4 * d, d)))))
        self.nf = nn.LayerNorm(d)
        self.head = nn.Linear(d, V, bias=False)
        self.ctx = ctx

    def n_params(self):
        """Non-embedding parameters, which is what scaling laws count."""
        tot = sum(p.numel() for p in self.parameters())
        emb = self.emb.weight.numel() + self.pos.weight.numel() + self.head.weight.numel()
        return tot - emb

    def forward(self, x):
        n = x.shape[1]
        h = self.emb(x) + self.pos(torch.arange(n))[None]
        m = torch.triu(torch.ones(n, n, dtype=torch.bool), 1)
        for b in self.blocks:
            a = b["n1"](h)
            h = h + b["att"](a, a, a, attn_mask=m, need_weights=False)[0]
            h = h + b["ff"](b["n2"](h))
        return self.head(self.nf(h))


def train_one(d, L, tokens, data, steps=None, ctx=64, bs=32, lr=3e-3,
              sched_tokens=None, seed=0, eval_data=None):
    """Train one model on `tokens` tokens drawn from `data`.

    `sched_tokens` sets the length of the cosine schedule. When it equals
    `tokens` the schedule is matched to the budget; when it is larger, the run
    stops partway down the cosine — which is exactly the error section 11 is
    about.
    """
    torch.manual_seed(seed)
    m = Tiny(d, L, ctx=ctx)
    per_step = bs * ctx
    steps = steps or max(20, int(tokens // per_step))
    sched_steps = max(steps, int((sched_tokens or tokens) // per_step))
    opt = torch.optim.AdamW(m.parameters(), lr=lr, weight_decay=0.01,
                            betas=(0.9, 0.95))
    warm = max(5, int(0.02 * sched_steps))

    def lr_at(s):
        if s < warm:
            return (s + 1) / warm
        p = (s - warm) / max(1, sched_steps - warm)
        return 0.1 + 0.45 * (1 + np.cos(np.pi * min(p, 1.0)))

    sch = torch.optim.lr_scheduler.LambdaLR(opt, lr_at)
    D = torch.tensor(data)
    usable = len(D) - ctx - 1
    r = np.random.default_rng(seed)
    for s in range(steps):
        i = torch.tensor(r.integers(0, usable, bs))
        x = torch.stack([D[j:j + ctx] for j in i])
        y = torch.stack([D[j + 1:j + ctx + 1] for j in i])
        loss = F.cross_entropy(m(x).reshape(-1, V), y.reshape(-1))
        opt.zero_grad(); loss.backward()
        torch.nn.utils.clip_grad_norm_(m.parameters(), 1.0)
        opt.step(); sch.step()
    E = torch.tensor(eval_data)
    with torch.no_grad():
        tot, cnt = 0.0, 0
        for j in range(0, min(len(E) - ctx - 1, 40000), ctx):
            x = E[j:j + ctx][None]; y = E[j + 1:j + ctx + 1][None]
            tot += float(F.cross_entropy(m(x).reshape(-1, V), y.reshape(-1))) * ctx
            cnt += ctx
    return m.n_params(), tot / cnt, steps


# --------------------------------------------------- 5. the scaling law

def fig_scaling():
    """A power law fitted to real runs, on a source whose entropy is known —
    so the irreducible term has a right answer."""
    P = make_source(0)
    H, _ = entropy_rate(P)
    print(f"    the source's exact entropy rate: {H:.4f} nats/token")
    train = sample_source(P, 400000, seed=1)
    ev = sample_source(P, 60000, seed=2)

    SIZES = [(16, 1), (24, 2), (40, 2), (64, 3), (96, 4)]
    TOK = 12_000_000
    LRS = [1e-3, 3e-3, 1e-2]
    pts = []
    for d, L in SIZES:
        # tune the learning rate at every size. Using one rate across sizes
        # makes the large models look worse than they are, which is a smaller
        # version of exactly the methodological error section 11 is about.
        best = None
        for lr in LRS:
            n, loss, steps = train_one(d, L, TOK, train, lr=lr, eval_data=ev)
            if best is None or loss < best[1]:
                best = (n, loss, lr)
        n, loss, lr = best
        pts.append((n, loss))
        print(f"      d={d:3d} L={L}  N={n:8,d}  best lr {lr:.0e}  loss {loss:.4f}  "
              f"excess over entropy {loss - H:.4f}")

    Ns = np.array([p[0] for p in pts], float)
    Ls = np.array([p[1] for p in pts], float)

    # fit L = A * N^-alpha + E, with E free
    from scipy.optimize import curve_fit
    f = lambda N, logA, alpha, E: np.exp(logA) * N ** (-alpha) + E
    (logA, alpha, E), _ = curve_fit(f, Ns, Ls, p0=[2.0, 0.3, H],
                                    maxfev=200000)
    # and with E pinned to the truth, for comparison
    g = lambda N, logA, alpha: np.exp(logA) * N ** (-alpha) + H
    (logA2, alpha2), _ = curve_fit(g, Ns, Ls, p0=[2.0, 0.3], maxfev=200000)

    print(f"    fitted:  alpha {alpha:.3f}   irreducible E {E:.4f}")
    print(f"    truth:                        entropy    {H:.4f}   "
          f"(error {abs(E-H):.4f}, {abs(E-H)/H*100:.1f}%)")
    print(f"    with E pinned to the truth, alpha = {alpha2:.3f}")

    fig, axes = plt.subplots(1, 2, figsize=(9.4, 3.5))
    ax = axes[0]
    grid = np.logspace(np.log10(Ns.min() * 0.7), np.log10(Ns.max() * 1.6), 100)
    ax.plot(Ns, Ls, "o", color=BLUE, ms=6, label="measured")
    ax.plot(grid, f(grid, logA, alpha, E), color=ORANGE, lw=1.7,
            label=f"fit: $L = AN^{{-{alpha:.2f}}} + {E:.3f}$")
    ax.axhline(H, color=GRAY, lw=1.4, ls="--",
               label=f"true entropy {H:.3f}")
    ax.set_xscale("log")
    ax.set_xlabel("non-embedding parameters $N$")
    ax.set_ylabel("test loss (nats/token)")
    ax.set_title("A scaling law, fitted", fontsize=10.5, color=INK)
    ax.legend(fontsize=7.4, frameon=False)
    tidy(ax)

    ax = axes[1]
    ax.plot(Ns, Ls - H, "o-", color=PURPLE, lw=1.8, ms=5)
    ax.plot(grid, f(grid, logA, alpha, E) - H, color=ORANGE, lw=1.4, ls="--")
    ax.set_xscale("log"); ax.set_yscale("log")
    ax.set_xlabel("non-embedding parameters $N$")
    ax.set_ylabel("loss above the entropy")
    ax.set_title("The reducible part is the power law",
                 fontsize=10.5, color=INK)
    tidy(ax)

    print("    subtracting the known entropy turns a curve into a straight line on")
    print("    log-log axes — which is the check that the law is a power law at all,")
    print("    and it is unavailable on real data because E is never known.")
    fig.tight_layout()
    # Project Stage 4 output, not a book figure — no book section references
    # it, so it is kept out of the numbered figures/sc/ namespace entirely.
    save(fig, "scaling-law-study", out_dir=STUDY_OUT)
    return dict(H=H, alpha=float(alpha), E=float(E), pts=pts)


# -------------------------------------------- 6. the learning-rate schedule

def fig_schedule():
    """Chinchilla's methodological correction, reproduced. Kaplan's runs used a
    cosine schedule tuned for the LONGEST budget and stopped short for smaller
    budgets — which penalises the short runs and biases the inferred optimum
    toward large models and too little data."""
    P = make_source(0)
    H, _ = entropy_rate(P)
    train = sample_source(P, 600000, seed=1)
    ev = sample_source(P, 60000, seed=2)

    d, L = 48, 2
    LONG = 2_400_000
    budgets = [150_000, 300_000, 600_000, 1_200_000, 2_400_000]
    matched, fixed = [], []
    for t in budgets:
        _, lm, _ = train_one(d, L, t, train, sched_tokens=t, eval_data=ev)
        _, lf, _ = train_one(d, L, t, train, sched_tokens=LONG, eval_data=ev)
        matched.append(lm); fixed.append(lf)
        print(f"      budget {t:9,d}: matched schedule {lm:.4f}   "
              f"fixed-length schedule {lf:.4f}   penalty {lf-lm:+.4f}")

    fig, axes = plt.subplots(1, 2, figsize=(9.4, 3.5))
    ax = axes[0]
    ax.plot(budgets, matched, "o-", color=GREEN, lw=1.9, ms=5,
            label="schedule matched to budget")
    ax.plot(budgets, fixed, "s-", color=ORANGE, lw=1.9, ms=5,
            label=f"schedule fixed at {LONG//1000}k, stopped early")
    ax.axhline(H, color=GRAY, lw=1.3, ls="--", label="entropy")
    ax.set_xscale("log")
    ax.set_xlabel("training tokens"); ax.set_ylabel("test loss")
    ax.set_title("The same runs, two schedules", fontsize=10.5, color=INK)
    ax.legend(fontsize=7.2, frameon=False)
    tidy(ax)

    ax = axes[1]
    pen = np.array(fixed) - np.array(matched)
    ax.plot(budgets, pen, "o-", color=PURPLE, lw=1.9, ms=5)
    ax.axhline(0, color=GRAY, lw=1.0, ls="--")
    ax.set_xscale("log")
    ax.set_xlabel("training tokens")
    ax.set_ylabel("loss penalty from the wrong schedule")
    ax.set_title("It penalises the short runs most", fontsize=10.5, color=INK)
    tidy(ax)

    print(f"    the penalty at the smallest budget is {pen[0]:+.4f} nats and at the")
    print(f"    largest is {pen[-1]:+.4f}. It is not a constant offset — it is a")
    print("    systematic tilt against short runs, which is exactly what biases the")
    print("    fitted optimum toward bigger models trained on less data.")
    fig.tight_layout()
    # Project Stage 5 output, not a book figure — the book's own schedule-error
    # figure is the illustrative 02-schedule-illus.svg. Kept out of figures/sc/.
    save(fig, "schedule-error-study", out_dir=STUDY_OUT)
    return dict(budgets=budgets, matched=matched, fixed=fixed, H=H)


# ------------------------------------------------------ 7. MoE load balancing

class MoEBlock(nn.Module):
    def __init__(self, d, n_exp=8, k=1):
        super().__init__()
        self.router = nn.Linear(d, n_exp, bias=False)
        self.experts = nn.ModuleList([
            nn.Sequential(nn.Linear(d, 2 * d), nn.GELU(), nn.Linear(2 * d, d))
            for _ in range(n_exp)])
        self.n_exp, self.k = n_exp, k

    def forward(self, x):
        B, T, D = x.shape
        flat = x.reshape(-1, D)
        logits = self.router(flat)
        probs = F.softmax(logits, -1)
        top = probs.topk(self.k, dim=-1)
        out = torch.zeros_like(flat)
        counts = torch.zeros(self.n_exp)
        for j in range(self.k):
            idx, w = top.indices[:, j], top.values[:, j]
            for e in range(self.n_exp):
                sel = idx == e
                counts[e] += float(sel.sum())
                if sel.any():
                    out[sel] += w[sel, None] * self.experts[e](flat[sel])
        # the standard auxiliary loss: fraction routed x mean probability
        frac = torch.stack([(top.indices[:, 0] == e).float().mean()
                            for e in range(self.n_exp)])
        aux = self.n_exp * (frac * probs.mean(0)).sum()
        return out.reshape(B, T, D), aux, counts


class MoETiny(nn.Module):
    def __init__(self, d=48, n_exp=8, ctx=64):
        super().__init__()
        self.emb = nn.Embedding(V, d); self.pos = nn.Embedding(ctx, d)
        self.n1, self.n2 = nn.LayerNorm(d), nn.LayerNorm(d)
        self.att = nn.MultiheadAttention(d, 2, batch_first=True)
        self.moe = MoEBlock(d, n_exp)
        self.nf = nn.LayerNorm(d); self.head = nn.Linear(d, V, bias=False)

    def forward(self, x):
        n = x.shape[1]
        h = self.emb(x) + self.pos(torch.arange(n))[None]
        a = self.n1(h)
        m = torch.triu(torch.ones(n, n, dtype=torch.bool), 1)
        h = h + self.att(a, a, a, attn_mask=m, need_weights=False)[0]
        o, aux, counts = self.moe(self.n2(h))
        return self.head(self.nf(h + o)), aux, counts


def fig_moe():
    """What a router does to expert load, with and without being told to
    balance — and what a fixed capacity then drops."""
    P = make_source(0)
    train = sample_source(P, 300000, seed=1)
    D = torch.tensor(train)
    N_EXP, CTX, BS = 8, 64, 32

    def run(aux_w, steps=1200, seed=0):
        torch.manual_seed(seed)
        m = MoETiny(n_exp=N_EXP, ctx=CTX)
        opt = torch.optim.AdamW(m.parameters(), lr=3e-3, weight_decay=0.01)
        r = np.random.default_rng(seed)
        usable = len(D) - CTX - 1
        for s in range(steps):
            i = torch.tensor(r.integers(0, usable, BS))
            x = torch.stack([D[j:j + CTX] for j in i])
            y = torch.stack([D[j + 1:j + CTX + 1] for j in i])
            logits, aux, _ = m(x)
            loss = F.cross_entropy(logits.reshape(-1, V), y.reshape(-1)) + aux_w * aux
            opt.zero_grad(); loss.backward(); opt.step()
        with torch.no_grad():
            tot = torch.zeros(N_EXP)
            for _ in range(20):
                i = torch.tensor(r.integers(0, usable, BS))
                x = torch.stack([D[j:j + CTX] for j in i])
                tot += m(x)[2]
        return (tot / tot.sum()).numpy()

    off = run(0.0)
    on = run(0.01)
    for nm, w in (("no balancing loss", off), ("with balancing loss", on)):
        frac = np.sort(w)[::-1]
        print(f"    {nm:22s} busiest expert {frac[0]*100:5.1f}%  "
              f"quietest {frac[-1]*100:5.1f}%  "
              f"max/mean {frac[0]*N_EXP:.2f}  "
              f"experts below 1% of tokens: {(w < 0.01).sum()}")

    caps = np.linspace(1.0, 2.0, 21)
    def dropped(w, cf):
        cap = cf / N_EXP
        return float(np.clip(w - cap, 0, None).sum())
    d_off = [dropped(off, c) for c in caps]
    d_on = [dropped(on, c) for c in caps]

    fig, axes = plt.subplots(1, 2, figsize=(9.4, 3.5))
    ax = axes[0]
    x = np.arange(N_EXP); wd = 0.38
    ax.bar(x - wd/2, np.sort(off)[::-1] * 100, wd, color=ORANGE, label="no balancing loss")
    ax.bar(x + wd/2, np.sort(on)[::-1] * 100, wd, color=GREEN, label="with balancing loss")
    ax.axhline(100 / N_EXP, color=GRAY, lw=1.2, ls="--")
    ax.text(N_EXP - 0.6, 100 / N_EXP + 1.2, "uniform", fontsize=8, color=GRAY, ha="right")
    ax.set_xticks(x); ax.set_xticklabels([f"{i+1}" for i in range(N_EXP)], fontsize=8)
    ax.set_xlabel("expert, busiest first"); ax.set_ylabel("% of tokens")
    ax.set_title("Where the tokens go", fontsize=10.5, color=INK)
    ax.legend(fontsize=7.6, frameon=False)
    tidy(ax)

    ax = axes[1]
    ax.plot(caps, np.array(d_off) * 100, "o-", color=ORANGE, lw=1.8, ms=3.5,
            label="no balancing loss")
    ax.plot(caps, np.array(d_on) * 100, "s-", color=GREEN, lw=1.8, ms=3.5,
            label="with balancing loss")
    ax.set_xlabel("capacity factor"); ax.set_ylabel("% of tokens dropped")
    ax.set_title("What a fixed capacity discards", fontsize=10.5, color=INK)
    ax.legend(fontsize=7.6, frameon=False)
    tidy(ax)

    print(f"    at capacity factor 1.0: {d_off[0]*100:.1f}% of tokens dropped without the")
    print(f"    balancing loss, {d_on[0]*100:.1f}% with it. Dropped tokens pass through the")
    print("    residual with no expert applied, and nothing in the loss curve says so.")
    fig.tight_layout()
    # This IS a book figure — Figure 7, referenced by 3308-sc-50-moe.html —
    # so it must land in figures/sc/ under the name the book ships and cites.
    save(fig, "07-moe")
    return dict(off=off.tolist(), on=on.tolist(), caps=caps.tolist(),
                d_off=d_off, d_on=d_on)


EXPENSIVE = [fig_scaling, fig_schedule, fig_moe]


if __name__ == "__main__":
    for f in EXPENSIVE:
        f()
